name: build

on:
  push:
    branches: ["main", "CI"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pango
        run: sudo apt-get install -y libgtk-3-dev libpango1.0-dev
      - name: Build
        run: cargo build --verbose
